version: '3.8'

services:
  db:
    image: postgres:13
    container_name: inventory_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: server_inventory
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - inventory_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: inventory_backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - DB_HOST=db
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - inventory_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: inventory_frontend
    ports:
      - "3000:80"  # Mapear al puerto 80 de nginx
    depends_on:
      - backend
    networks:
      - inventory_network

volumes:
  db_data:

networks:
  inventory_network:
    driver: bridge